POST http://localhost:8750/login
Content-Type: application/json

{
  "email": "thethiago27@gmail.com",
  "password": "Thiago360*"
}

> {% client.global.set("auth_token", response.body.token); %}


### Get all contacts [GET] /contact

GET http://localhost:8750/contact
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

### Create a new contact [POST] /contact

POST http://localhost:8750/contact
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
  "name": "Pedro",
  "email": "pedro@gmail.com",
  "phone": "65984432583",
  "type": "personal",
  "address": {
    "rua": "3",
    "numero": "20",
    "bairro": "Mirante do Parque",
    "cidade": "Cuiabá",
    "estado": "Mato Grosso",
    "cep": "78091515"
  },
  "birthday": "2001-11-14"
}



###
